# Generated by Django 4.0.3 on 2022-03-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('numero_identificacion', models.CharField(max_length=15, verbose_name='numero de identificacion')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('telefono', models.IntegerField(null=True, verbose_name='telefono')),
                ('celular', models.IntegerField(null=True, verbose_name='celular')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Habitacion')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion')),
                ('numero', models.PositiveIntegerField(verbose_name='numero')),
                ('piso', models.PositiveIntegerField(verbose_name='piso')),
                ('precio_dia', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='precio_dia')),
                ('estado_habitacion', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], default='Bueno', max_length=30, verbose_name='estado')),
            ],
            options={
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
