# Generated by Django 4.0.3 on 2022-03-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservar', '0002_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modo_Pago',
            fields=[
                ('id_modo_pago', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Modo Pago')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('detalles', models.CharField(max_length=30, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'Modo_Pago',
            },
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Receta', 'verbose_name_plural': 'Reservas'},
        ),
    ]
