# Generated by Django 4.0.3 on 2022-03-18 21:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservar', '0003_modo_pago_alter_reserva_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Factura')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de Entrada')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservar.cliente', verbose_name='Cliente')),
                ('id_modo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservar.modo_pago', verbose_name='modo_pago')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservar.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
